apiVersion: v1
kind: Service
metadata:
  name: myimagesrv
  labels:
    app: my-app 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app 
  template:
    metadata:
      labels:
        app: my-app 
    spec:
      containers:
      - name: my-app
        image: default/my-image:1.2
        ports:
        - containerPort: 80