apiVersion: v1
kind: Service
metadata:
  name: my-image_srv
  labels:
    app: my-image 
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-image 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-image 
  template:
    metadata:
      labels:
        app: my-image 
    spec:
      containers:
      - name: my-image
        image: default/my-image:1.0
        ports:
        - containerPort: 80